struct stat;
struct rtcdate;

// system calls
int fork(void);
int exit(void) __attribute__((noreturn));
int wait(void);
int pipe(int*);
int write(int, void*, int);
int read(int, void*, int);
int close(int);
int kill(int);
int exec(char*, char**);
int open(char*, int);
int mknod(char*, short, short);
int unlink(char*);
int fstat(int fd, struct stat*);
int link(char*, char*);
int mkdir(char*);
int chdir(char*);
int dup(int);
int getpid(void);
char* sbrk(int);
int sleep(int);
int uptime(void);

int date(struct rtcdate *r);
int ls_call01(void);
int ls_call02(void);
int ls_call03(void);
int ls_call04(void);
int ls_call05(void);
int ls_call06(void);
int ls_call07(void);
int ls_call08(void);
int ls_call09(void);
int ls_call10(void);
int ls_call11(void);
int ls_call12(void);
int ls_call13(void);
int ls_call14(void);
int ls_call15(void);
int ls_call16(void);
int ls_call17(void);
int ls_call18(void);
int ls_call19(void);
int ls_call20(void);
int ls_call21(void);
int ls_call22(void);
int ls_call23(void);
int ls_call24(void);
int ls_call25(void);
int ls_call26(void);
int ls_call27(void);
int ls_call28(void);
int ls_call29(void);
int ls_call30(void);

// ulib.c
int stat(char*, struct stat*);
char* strcpy(char*, char*);
void *memmove(void*, void*, int);
char* strchr(const char*, char c);
int strcmp(const char*, const char*);
void printf(int, char*, ...);
char* gets(char*, int max);
uint strlen(char*);
void* memset(void*, int, uint);
void* malloc(uint);
void free(void*);
int atoi(const char*);
